[project]
name = "vehiclemodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pint>=0.25.2",
    "pyyaml>=6.0.3",
]
